---

- name: Prepare group sftp_users
  ansible.builtin.group:
    name: "sftp_users"

- name: "Add config block"
  when: (opts_sftp_config.add_config_block is defined) and opts_sftp_config.add_config_block
  vars:
    sftp_config_opts: "{{ opts_sftp_config | combine(gz_ssh_config,recursive=True) }}"
  blockinfile:
    #block: "{{ lookup('file', opts_sshd_config.block) }}"
    block: |
      #Prepare for jailed sftp account
      Match Group sftp_users
        ChrootDirectory /chroot/%u/www
        ForceCommand internal-sftp
        PasswordAuthentication yes
        AllowAgentForwarding no
        AllowTcpForwarding no
        X11Forwarding no
        PermitTunnel no
    path: "{{sftp_config_opts.sshd_config.file}}"
    marker: "#{mark} {{sftp_config_opts.sshd_config.marker_text}}"
    insertafter: "{{sftp_config_opts.sshd_config.insertafter}}"
    backup: "{{sftp_config_opts.sshd_config.backup}}"
    validate: "{{sftp_config_opts.sshd_config.validate}}"
  tags: [ssh_cfg]
  notify:
    - "restart ssh"

- name: "Del config block"
  when: opts_sshd_config.del_config_block is defined
  blockinfile:
    block: ''
    path: "{{sftp_config_opts.sshd_config.file}}"
    marker: "#{mark} {{sftp_config_opts.sshd_config.marker_text}}"
    insertafter: "{{sftp_config_opts.sshd_config.insertafter}}"
    backup: "{{sftp_config_opts.sshd_config.backup}}"
    validate: "{{sftp_config_opts.sshd_config.validate}}"
  tags: [ssh_cfg_del,never]
  notify:
    - "restart ssh"