---

- name: Create a user & corresponding setup
  vars:
    opts_user: "{{opts_user | combine(opts_ssh.user,recursive=True) }}"
  block:
  - name: Add the user's group
    ansible.builtin.group:
      name: "{{opts_user.group}}"

  - name: Add the user
    vars:
      pw_hashed: "{{ opts_user.pass | password_hash('sha512') }}"
      home_dir:  "/home/{{opts_user.user}}/"
    block:
    - name: Stop services
      ignore_errors: yes
      vars:
        opts_common:
          services:
            state: stopped
            service_items:
            - 'php7.4-fpm'
      include_role: name=gz_common
    - name: Add user
      ansible.builtin.user:
        name: "{{opts_user.user}}"
        password: "{{ pw_hashed }}"
        group: "{{ opts_user.group | default(omit) }}"
        groups: sftp_users
        append: yes
        create_home: "{{ opts_user.create_home | default(omit) }}"
        home:        "{{ opts_user.home_dir | default(omit) }}"
    - name: Start services
      ignore_errors: yes
      vars:
        opts_common:
          services:
            state: started
            service_items:
            - 'php7.4-fpm'
      include_role: name=gz_common

  - name: create_dirs
    loop: "{{ q('dict',opts_user.create_dirs.dir_items) }}"
    loop_control: {loop_var: _user_dir_item }
    vars:
      user_dir_item: "{{_user_dir_item.value}}"
      opts_create_dirs_v2:
      - path: "{{user_dir_item.src}}"
        owner: "{{opts_user.user}}"
        group: "{{opts_user.group}}"
        mode: "{{opts_user.create_dirs.dir_opts.mode | default(omit) }}"
    include_role: {name: gz_common ,tasks_from: create_dirs_v2.yml}

  - name: Create & mount dirs
    when: (opts_user.site_dir is defined)
    vars:
      opt_rw: "bind,rw,auto,gid={{opts_user.group}},uid={{opts_user.user}}"
      opt_ro: "bind,ro,auto,gid={{opts_user.group}},uid={{opts_user.user}}"
      opts_common:
        create_dirs_v2:
        - {path: "{{opts_user.mount_dir}}" ,owner: "{{opts_user.user}}" ,group: "{{opts_user.user}}"  ,mode: 'u=rw,g=r,o=r' ,recurse: yes }
        mounts_v2:
        - {path: "{{opts_user.mount_dir}}" ,src: "{{opts_user.site_dir}}" ,state: 'mounted' ,fstype: 'none' ,opts: "{{opt_rw}}" }
    include_role: {name: gz_common}
####################################
